baseURL = 'https://ismantic.github.io/'
languageCode = 'en-us'
title = 'Isma 是语'
theme = "PaperMod"

[params]
    author = "Ismantic"
    hideSummary = true
    hideAuthor = true

[author]
    name = "Ismantic"
